;this file for FamiTone2 library generated by text2data tool

ballzytunes_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,256,213

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env4,@env6,@env0
	.byte $00
	.byte $70 ;instrument $04
	.word @env5,@env0,@env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;1
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;2
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24
	.byte $00+.lobyte(FT_DPCM_PTR),$01,$04	;25
	.byte $01+.lobyte(FT_DPCM_PTR),$01,$04	;26
	.byte $0a+.lobyte(FT_DPCM_PTR),$12,$0f	;27
	.byte $17+.lobyte(FT_DPCM_PTR),$24,$0f	;28
	.byte $0f+.lobyte(FT_DPCM_PTR),$1c,$0f	;29
	.byte $21+.lobyte(FT_DPCM_PTR),$04,$0b	;30
	.byte $23+.lobyte(FT_DPCM_PTR),$08,$0d	;31
	.byte $02+.lobyte(FT_DPCM_PTR),$07,$0f	;32
	.byte $02+.lobyte(FT_DPCM_PTR),$07,$0e	;33
	.byte $04+.lobyte(FT_DPCM_PTR),$0f,$0f	;34
	.byte $08+.lobyte(FT_DPCM_PTR),$05,$0d	;35
	.byte $21+.lobyte(FT_DPCM_PTR),$04,$0c	;36
	.byte $04+.lobyte(FT_DPCM_PTR),$0f,$4f	;37
	.byte $23+.lobyte(FT_DPCM_PTR),$08,$4d	;38
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $cc,$ca,$c9,$c7,$03,$c7,$00,$05
@env3:
	.byte $cf,$cc,$ca,$ca,$c9,$c8,$c7,$c8,$00,$07
@env4:
	.byte $cb,$cb,$c7,$c4,$00,$03
@env5:
	.byte $c4,$c2,$c1,$04,$c1,$00,$04
@env6:
	.byte $c0,$c5,$c0,$00,$02


@song0ch0:
	.byte $fb,$03
@ref0:
	.byte $fb,$03,$82,$3a,$85,$53,$48,$85,$41,$52,$85,$3b,$41,$52,$85,$3b
	.byte $41,$52,$85,$3a,$85,$53,$4a,$85,$45,$52,$85,$3b,$45,$52,$85,$3b
	.byte $45,$53,$4a,$81
@ref1:
	.byte $3c,$85,$55,$4a,$85,$45,$54,$85,$3d,$45,$54,$85,$3d,$45,$54,$85
	.byte $40,$85,$59,$4e,$85,$49,$58,$85,$41,$49,$58,$85,$41,$4b,$49,$42
	.byte $81
@song0ch0loop:
@ref2:
	.byte $82,$3b,$41,$53,$49,$3b,$41,$53,$49,$3b,$41,$53,$49,$3b,$41,$53
	.byte $49,$3b,$45,$53,$4b,$3b,$45,$53,$4b,$3b,$45,$53,$4b,$3b,$45,$53
	.byte $4a,$81
@ref3:
	.byte $3d,$45,$55,$4b,$3d,$45,$55,$4b,$3d,$45,$55,$4b,$3d,$45,$55,$4b
	.byte $41,$49,$59,$4f,$41,$49,$59,$4f,$41,$49,$59,$4f,$41,$4b,$49,$42
	.byte $81
@ref4:
	.byte $3b,$41,$53,$49,$3b,$41,$53,$49,$3b,$41,$53,$49,$3b,$41,$53,$49
	.byte $3b,$45,$53,$4b,$3b,$45,$53,$4b,$3b,$45,$53,$4b,$3b,$45,$53,$4a
	.byte $81
	.byte $ff,$21
	.word @ref3
@ref6:
	.byte $61,$41,$53,$49,$3b,$41,$53,$49,$3b,$41,$53,$49,$3b,$41,$53,$49
	.byte $3b,$45,$53,$4b,$3b,$45,$53,$4b,$3b,$45,$53,$4b,$3b,$45,$53,$4a
	.byte $81
	.byte $ff,$21
	.word @ref3
	.byte $ff,$21
	.word @ref4
	.byte $ff,$21
	.word @ref3
	.byte $ff,$21
	.word @ref6
	.byte $ff,$21
	.word @ref3
	.byte $ff,$21
	.word @ref4
	.byte $ff,$21
	.word @ref3
@ref14:
	.byte $5d,$01,$45,$01,$5d,$01,$45,$01,$5d,$01,$45,$01,$5d,$01,$45,$01
	.byte $5d,$01,$45,$01,$5d,$01,$45,$01,$5d,$01,$45,$01,$5c,$00,$60,$00
	.byte $62,$00,$66,$00
@ref15:
	.byte $5d,$01,$45,$01,$5d,$01,$45,$01,$5d,$01,$45,$01,$5d,$01,$45,$01
	.byte $5d,$01,$45,$01,$5d,$01,$45,$01,$5d,$01,$45,$01,$4a,$00,$48,$00
	.byte $44,$00,$40,$00
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref16:
	.byte $f9,$85
@ref17:
	.byte $f9,$85
@song0ch1loop:
@ref18:
	.byte $82,$44,$95,$3b,$01,$3a,$99,$44,$48,$4a,$85,$48,$85,$44,$85,$40
	.byte $8d,$3a,$95
@ref19:
	.byte $44,$89,$3d,$00,$85,$40,$85,$44,$99,$40,$44,$48,$89,$4b,$00,$85
	.byte $4e,$85,$4a,$8d,$48,$8d
@ref20:
	.byte $44,$95,$3b,$01,$3a,$99,$44,$48,$4a,$85,$48,$85,$4a,$85,$4e,$8d
	.byte $58,$95
@ref21:
	.byte $44,$89,$49,$00,$85,$4a,$85,$4e,$8d,$4a,$85,$4e,$85,$58,$ad,$84
	.byte $1a,$85,$18,$85
@ref22:
	.byte $14,$ad,$82,$10,$8d,$14,$ad,$84,$1a,$8d
@ref23:
	.byte $1e,$b5,$82,$1a,$85,$10,$bd
@ref24:
	.byte $84,$14,$ad,$82,$10,$8d,$14,$ad,$84,$1a,$8d
	.byte $ff,$06
	.word @ref23
	.byte $ff,$08
	.word @ref24
	.byte $ff,$06
	.word @ref23
	.byte $ff,$08
	.word @ref24
@ref29:
	.byte $1e,$bd,$82,$10,$bd
@ref30:
	.byte $84,$14,$8d,$00,$ed
@ref31:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref32:
	.byte $f9,$85
@ref33:
	.byte $f9,$85
@song0ch2loop:
@ref34:
	.byte $00,$f9,$83
@ref35:
	.byte $f9,$85
@ref36:
	.byte $f9,$85
@ref37:
	.byte $f7,$82,$10,$85
@ref38:
	.byte $6a,$89,$5c,$89,$58,$85,$5c,$8d,$5d,$61,$63,$67,$70,$89,$6a,$89
	.byte $66,$85,$5c,$9d
@ref39:
	.byte $6a,$89,$62,$89,$60,$85,$5c,$8d,$58,$85,$60,$85,$70,$89,$66,$89
	.byte $62,$85,$58,$9d
@ref40:
	.byte $6a,$89,$5c,$89,$58,$85,$5c,$8d,$5d,$61,$63,$67,$70,$89,$6a,$89
	.byte $78,$85,$74,$9d
@ref41:
	.byte $7a,$89,$78,$89,$74,$85,$70,$95,$74,$85,$70,$9d,$7a,$89,$78,$89
	.byte $70,$85
	.byte $ff,$14
	.word @ref38
	.byte $ff,$14
	.word @ref39
	.byte $ff,$14
	.word @ref40
	.byte $ff,$12
	.word @ref41
@ref46:
	.byte $74,$6a,$62,$5c,$74,$6a,$62,$5c,$74,$6a,$62,$5c,$74,$6a,$62,$5c
	.byte $74,$6a,$62,$5c,$74,$6a,$62,$5c,$74,$6a,$62,$5c,$74,$6a,$62,$5c
	.byte $75,$00,$b9
@ref47:
	.byte $00,$f9,$83
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref48:
	.byte $f9,$85
@ref49:
	.byte $f9,$85
@song0ch3loop:
@ref50:
	.byte $f9,$85
@ref51:
	.byte $f9,$85
@ref52:
	.byte $f9,$85
@ref53:
	.byte $f9,$85
@ref54:
	.byte $f9,$85
@ref55:
	.byte $f9,$85
@ref56:
	.byte $f9,$85
@ref57:
	.byte $f9,$85
@ref58:
	.byte $f9,$85
@ref59:
	.byte $f9,$85
@ref60:
	.byte $f9,$85
@ref61:
	.byte $f9,$85
@ref62:
	.byte $f9,$85
@ref63:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref64:
	.byte $f9,$85
@ref65:
	.byte $f7,$47,$46,$81
@song0ch4loop:
@ref66:
	.byte $36,$89,$3b,$40,$85,$36,$85,$37,$36,$89,$3a,$85,$47,$46,$46,$36
	.byte $89,$3b,$40,$85,$36,$85,$37,$36,$89,$3a,$85,$46,$85
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
	.byte $ff,$1d
	.word @ref66
@ref78:
	.byte $f7,$47,$46,$81
	.byte $ff,$1d
	.word @ref66
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@ref80:
	.byte $fb,$02,$00,$f9,$83
@song1ch0loop:
@ref81:
	.byte $fb,$04,$86,$0a,$89,$11,$0a,$85,$00,$95,$19,$15,$11,$0f,$14,$89
	.byte $11,$14,$85,$00,$95,$10,$85,$0e,$85
@ref82:
	.byte $0a,$89,$11,$0a,$85,$00,$95,$19,$15,$11,$0f,$14,$89,$11,$14,$85
	.byte $00,$95,$10,$85,$0e,$85
	.byte $ff,$16
	.word @ref82
	.byte $ff,$16
	.word @ref82
	.byte $ff,$16
	.word @ref82
	.byte $ff,$16
	.word @ref82
@ref87:
	.byte $0a,$85,$00,$f5
@ref88:
	.byte $00,$f9,$83
@ref89:
	.byte $00,$f9,$83
@ref90:
	.byte $00,$f9,$83
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@ref91:
	.byte $00,$f9,$83
@song1ch1loop:
@ref92:
	.byte $00,$f9,$83
@ref93:
	.byte $00,$f9,$83
@ref94:
	.byte $88,$53,$59,$61,$6b,$79,$71,$6b,$61,$53,$59,$61,$6b,$79,$71,$6b
	.byte $61,$5d,$63,$6b,$75,$7b,$75,$6b,$63,$5d,$63,$6b,$75,$7b,$75,$6b
	.byte $70,$81
@ref95:
	.byte $53,$59,$61,$6b,$79,$71,$6b,$61,$53,$59,$61,$6b,$79,$71,$6b,$61
	.byte $5d,$63,$6b,$75,$7b,$75,$6b,$63,$5d,$63,$6b,$75,$7b,$75,$6b,$70
	.byte $81
	.byte $ff,$21
	.word @ref95
	.byte $ff,$21
	.word @ref95
@ref98:
	.byte $00,$f9,$83
@ref99:
	.byte $00,$f9,$83
@ref100:
	.byte $00,$f9,$83
@ref101:
	.byte $00,$f9,$83
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@ref102:
	.byte $00,$f9,$83
@song1ch2loop:
@ref103:
	.byte $00,$f9,$83
@ref104:
	.byte $00,$f9,$83
@ref105:
	.byte $00,$f9,$83
@ref106:
	.byte $00,$f9,$83
@ref107:
	.byte $00,$f9,$83
@ref108:
	.byte $00,$f9,$83
@ref109:
	.byte $00,$f9,$83
@ref110:
	.byte $00,$f9,$83
@ref111:
	.byte $00,$f9,$83
@ref112:
	.byte $00,$f9,$83
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@ref113:
	.byte $00,$f9,$83
@song1ch3loop:
@ref114:
	.byte $00,$f9,$83
@ref115:
	.byte $00,$f9,$83
@ref116:
	.byte $00,$f9,$83
@ref117:
	.byte $00,$f9,$83
@ref118:
	.byte $00,$f9,$83
@ref119:
	.byte $00,$f9,$83
@ref120:
	.byte $00,$f9,$83
@ref121:
	.byte $00,$f9,$83
@ref122:
	.byte $00,$f9,$83
@ref123:
	.byte $00,$f9,$83
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@ref124:
	.byte $00,$f9,$83
@song1ch4loop:
@ref125:
	.byte $36,$89,$37,$3a,$89,$36,$85,$36,$85,$37,$3a,$8d,$36,$89,$37,$3a
	.byte $89,$36,$85,$36,$85,$37,$3a,$89,$3a,$3a
	.byte $ff,$1a
	.word @ref125
	.byte $ff,$1a
	.word @ref125
	.byte $ff,$1a
	.word @ref125
	.byte $ff,$1a
	.word @ref125
	.byte $ff,$1a
	.word @ref125
	.byte $ff,$1a
	.word @ref125
@ref132:
	.byte $36,$89,$37,$3a,$89,$36,$85,$36,$85,$37,$3a,$8d,$36,$89,$37,$3a
	.byte $89,$36,$85,$36,$85,$37,$3a,$85,$3b,$3a,$81
@ref133:
	.byte $36,$f9,$83
@ref134:
	.byte $00,$f9,$83
	.byte $fd
	.word @song1ch4loop
